import streamlit as st
import json
import pandas as pd
import sys
import re

# Add workspace directory to python path
sys.path.append("c:/Users/varshini/age-viewer")
import query_to_age

# Page configuration
st.set_page_config(
    page_title="Apache AGE Semantic Layer Explorer",
    page_icon="🧠",
    layout="wide"
)

# Custom CSS for modern styling
st.markdown("""
<style>
    .main-title {
        font-size: 2.3rem;
        font-weight: 700;
        color: #1E293B;
        margin-bottom: 0.2rem;
    }
    .subtitle {
        font-size: 1.05rem;
        color: #64748B;
        margin-bottom: 1.5rem;
    }
    .kpi-card {
        background: linear-gradient(135deg, #EFF6FF 0%, #DBEAFE 100%);
        border: 1px solid #BFDBFE;
        border-radius: 12px;
        padding: 24px;
        text-align: center;
        margin: 15px 0;
    }
    .kpi-value {
        font-size: 2.8rem;
        font-weight: 800;
        color: #1E40AF;
    }
    .kpi-label {
        font-size: 1.1rem;
        font-weight: 600;
        color: #3B82F6;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
</style>
""", unsafe_allow_html=True)

# Helper function to parse AGE query results
def parse_age_results(rows):
    if not rows:
        return 'table', []

    first_val = str(rows[0][0])
    
    # Scalar aggregation result (e.g. 55000.0, 10, 13430.0, None)
    if "::vertex" not in first_val and len(rows) == 1:
        return 'scalar', first_val.strip()

    # Table result (list of vertex nodes)
    results = []
    seen = set()
    for row in rows:
        value = row[0]
        text = str(value)
        if "::vertex" in text:
            json_part = text.replace("::vertex", "").strip()
            try:
                data = json.loads(json_part)
                properties = data.get("properties", {})
                if properties:
                    pkey = json.dumps(properties, sort_keys=True)
                    if pkey not in seen:
                        seen.add(pkey)
                        results.append(properties)
            except Exception:
                results.append({"Result": text})
        else:
            results.append({"Result": text})

    return 'table', results

# Sidebar: Semantic Catalog Explorer
with st.sidebar:
    st.header("📖 Semantic Catalog")
    st.caption("Source of Truth (`semantic_catalog.json`)")
    
    cat_tables = query_to_age.tables
    cat_rels = query_to_age.relationships

    st.subheader(f"Tables ({len(cat_tables)})")
    for t in cat_tables:
        with st.expander(f"📌 {t['table'].title()}"):
            st.write(f"**Concept:** {t.get('business_concept', '')}")
            st.write(f"**Synonyms:** {', '.join(t.get('synonyms', []))}")
            st.markdown("**Columns:**")
            for c in t.get("columns", []):
                role = c.get("role", "attribute")
                st.caption(f"• `{c['column']}` ({role}): {c.get('meaning', '')}")

    st.subheader(f"Relationships ({len(cat_rels)})")
    for r in cat_rels:
        st.info(f"`{r['from_table']}` → `{r['to_table']}`\n\n({r['from_column']} = {r['to_column']})")

# Header Section
st.markdown("<div class='main-title'>Semantic Layer → Apache AGE Explorer</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Natural Language Knowledge Graph Query System for Apache PostgreSQL AGE</div>", unsafe_allow_html=True)

# Architecture Diagram Expander
with st.expander("🏗️ View Semantic Layer Pipeline Architecture", expanded=False):
    st.markdown("""
    ```
    Natural Language Question
            ↓
      Semantic Catalog (Source of Truth)
            ↓
      LLM Reasoning & Intent Resolution
            ↓
      Apache AGE Cypher Generation
            ↓
      Deterministic Catalog & Sanity Validation
            ↓
      Apache AGE Graph Execution
            ↓
      Structured Results & KPI Presentation
    ```
    """)

st.markdown("---")
st.subheader("❓ Ask a Natural Language Question")

# Initialize session state for user question if not set
if "user_question" not in st.session_state:
    st.session_state["user_question"] = ""

# Example questions list
example_questions = [
    "-- Select an example question --",
    "Show me all orders",
    "Show me orders placed by Kalyani",
    "Show me customers from Hyderabad",
    "Show me orders for Laptop",
    "Show me revenue generated by customers from Visakhapatnam for laptops",
    "What is the average order amount?",
    "What is the highest order amount?"
]

# Callback when dropdown is changed
def on_select_example():
    selected = st.session_state.get("example_dropdown")
    if selected and selected != "-- Select an example question --":
        st.session_state["user_question"] = selected

# Free-text input area for arbitrary questions
typed_text = st.text_input(
    "Type any question here:",
    key="user_question",
    placeholder="e.g. Which customer spent the most money?"
)

ask_button = st.button("🔍 Ask Question", type="primary")

# Example dropdown selector below text box
st.selectbox(
    "Or try an example question:",
    options=example_questions,
    key="example_dropdown",
    on_change=on_select_example
)

# Processing user question
if ask_button or st.session_state.get("run_query"):
    # Priority: Typed text in text box takes precedence if present
    question_to_process = typed_text.strip()
    
    if not question_to_process:
        selected = st.session_state.get("example_dropdown")
        if selected and selected != "-- Select an example question --":
            question_to_process = selected.strip()

    if question_to_process:
        st.markdown("---")
        st.subheader(f"🔍 Question Analysis: \"{question_to_process}\"")

        with st.spinner("Analyzing question with AI & generating Apache AGE Cypher..."):
            try:
                # 1. Semantic Context & Interpretation
                relevant_context = query_to_age.find_relevant_context(question_to_process)
                
                col_context, col_cypher = st.columns([1, 1])

                with col_context:
                    st.markdown("### 🧠 Semantic Interpretation")
                    rel_tables = [t['table'] for t in relevant_context.get('tables', [])]
                    st.write(f"**Identified Entities/Tables:** `{', '.join(rel_tables)}`")
                    
                    rels_text = [f"({r['from_table']}) -> ({r['to_table']})" for r in relevant_context.get('relationships', [])]
                    if rels_text:
                        st.write(f"**Active Relationships:** `{', '.join(rels_text)}`")
                    else:
                        st.write("**Active Relationships:** `Direct Node Query`")

                    # Extract metric/aggregation intent
                    q_lower = question_to_process.lower()
                    if "revenue" in q_lower or "total" in q_lower or "sum" in q_lower or "spent" in q_lower:
                        st.write("**Metric Intent:** `SUM / TOTAL MEASURE`")
                    elif "average" in q_lower or "avg" in q_lower:
                        st.write("**Metric Intent:** `AVG(order_amount)`")
                    elif "highest" in q_lower or "maximum" in q_lower or "max" in q_lower or "most" in q_lower:
                        st.write("**Metric Intent:** `MAX / HIGHEST AGGREGATE`")
                    elif "lowest" in q_lower or "minimum" in q_lower or "min" in q_lower:
                        st.write("**Metric Intent:** `MIN AGGREGATE`")
                    elif "how many" in q_lower or "count" in q_lower:
                        st.write("**Metric Intent:** `COUNT AGGREGATE`")
                    else:
                        st.write("**Metric Intent:** `ENTITY LIST / GRAPH TRAVERSAL`")

                # 2. Query Generation & Parsing
                raw_ai = query_to_age.generate_age_query(question_to_process)
                parsed = query_to_age.parse_ai_response(raw_ai, question_to_process)
                cypher_query = parsed.get("query", "")

                with col_cypher:
                    st.markdown("### ⚡ Generated Apache AGE Cypher")
                    st.code(cypher_query, language="cypher")

                # 3. Validation Stage
                st.markdown("### 🛡️ Validation & Execution")
                valid, val_message = query_to_age.validate_query(cypher_query, question_to_process)

                if valid:
                    st.success(f"✅ {val_message}")

                    # 4. Database Execution
                    rows = query_to_age.execute_age_query(cypher_query)
                    res_type, res_data = parse_age_results(rows)

                    st.markdown("### 📊 Execution Result")

                    if res_type == 'scalar':
                        # KPI Card Display for scalar metrics
                        val_str = str(res_data)
                        
                        kpi_label = "RESULT"
                        if "revenue" in q_lower or "total" in q_lower:
                            kpi_label = "TOTAL REVENUE"
                        elif "average" in q_lower or "avg" in q_lower:
                            kpi_label = "AVERAGE ORDER AMOUNT"
                        elif "highest" in q_lower or "max" in q_lower:
                            kpi_label = "HIGHEST AMOUNT"
                        elif "lowest" in q_lower or "min" in q_lower:
                            kpi_label = "LOWEST AMOUNT"
                        elif "how many" in q_lower or "count" in q_lower:
                            kpi_label = "TOTAL COUNT"

                        formatted_val = val_str
                        try:
                            val_num = float(val_str)
                            if "count" not in kpi_label.lower() and "how many" not in q_lower:
                                formatted_val = f"₹{val_num:,.2f}"
                            else:
                                formatted_val = f"{int(val_num):,}"
                        except Exception:
                            pass

                        st.markdown(f"""
                        <div class="kpi-card">
                            <div class="kpi-label">{kpi_label}</div>
                            <div class="kpi-value">{formatted_val}</div>
                        </div>
                        """, unsafe_allow_html=True)

                    else:
                        # Tabular display for entity objects
                        if not res_data:
                            st.info("No matching records found in Apache AGE graph.")
                        else:
                            df = pd.DataFrame(res_data)
                            
                            if "_table" in df.columns:
                                cols = ["_table"] + [c for c in df.columns if c != "_table"]
                                df = df[cols]

                            st.write(f"**Found {len(df)} matching records:**")
                            st.dataframe(df, width=1000)

                else:
                    st.error(f"❌ Validation Failed: {val_message}")
                    st.warning("Query execution was blocked to preserve graph integrity.")

            except Exception as e:
                st.error(f"Execution Error: {str(e)}")
                if query_to_age.conn:
                    query_to_age.conn.rollback()

    else:
        st.warning("Please enter a question in the text box or select an example question above.")
